DROP TABLE EVENTO_ESTUDIANTE CASCADE CONSTRAINTS;
DROP TABLE EVENTO_PROFESOR CASCADE CONSTRAINTS;
DROP TABLE LOG_ASIGNACIONES CASCADE CONSTRAINTS;
DROP TABLE EVENTO CASCADE CONSTRAINTS;
DROP TABLE ESTUDIANTE CASCADE CONSTRAINTS;
DROP TABLE PROYECTO CASCADE CONSTRAINTS;
DROP TABLE TRACK CASCADE CONSTRAINTS;
DROP TABLE PROFESOR CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_EVENTO;
DROP SEQUENCE SEQ_PROFESOR;
DROP SEQUENCE SEQ_TRACK;
DROP SEQUENCE SEQ_PROYECTO;

-- TABLA DE PROFESORES
CREATE TABLE PROFESOR (
    id_profesor NUMBER PRIMARY KEY,
    pnombre     VARCHAR2(50) NOT NULL,
    papellido   VARCHAR2(50) NOT NULL,
    rut         NUMBER UNIQUE NOT NULL
);

-- TABLA DE TRACKS (CATEGORÍAS DE PROYECTOS)
CREATE TABLE TRACK (
    id_track      NUMBER PRIMARY KEY,
    nombre        VARCHAR2(100) UNIQUE NOT NULL,
    id_profesor   NUMBER,
    FOREIGN KEY (id_profesor) REFERENCES PROFESOR(id_profesor)
);

-- TABLA DE PROYECTOS
CREATE TABLE PROYECTO (
    id_proyecto   NUMBER PRIMARY KEY,
    nombre        VARCHAR2(150) NOT NULL,
    descripcion   VARCHAR2(500) NOT NULL,
    id_track      NUMBER,
    FOREIGN KEY (id_track) REFERENCES TRACK(id_track)
);

-- TABLA DE ESTUDIANTES
CREATE TABLE ESTUDIANTE (
    numrun      NUMBER PRIMARY KEY NOT NULL,
    dv_run      CHAR(1) NOT NULL,
    pnombre     VARCHAR2(50) NOT NULL,
    snombre     VARCHAR2(50) NOT NULL,
    papellido   VARCHAR2(50) NOT NULL,
    mapellido   VARCHAR2(50) NOT NULL,
    fec_nac     DATE NOT NULL,
    id_genero   NUMBER NOT NULL, -- 1: Femenino, 2: Masculino
    id_proyecto NUMBER, -- Puede ser NULL
    FOREIGN KEY (id_proyecto) REFERENCES PROYECTO(id_proyecto)
);

-- TABLA DE EVENTOS
CREATE TABLE EVENTO (
    id_evento   NUMBER PRIMARY KEY,
    nombre      VARCHAR2(150) NOT NULL,
    lugar       VARCHAR2(100) NOT NULL,
    fecha       DATE NOT NULL,
    hora_inicio VARCHAR2(5) NOT NULL, -- Formato HH24:MI
    hora_fin    VARCHAR2(5) NOT NULL  -- Formato HH24:MI
);

CREATE TABLE LOG_ASIGNACIONES (
    id_log       NUMBER GENERATED ALWAYS AS IDENTITY,
    rut_estudiante NUMBER,
    id_proyecto  NUMBER,
    fecha_asig   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id_log)
);

-- TABLA INTERMEDIA: EVENTO <-> PROFESOR
CREATE TABLE EVENTO_PROFESOR (
    id_evento     NUMBER,
    id_profesor   NUMBER,
    PRIMARY KEY (id_evento, id_profesor),
    FOREIGN KEY (id_evento) REFERENCES EVENTO(id_evento),
    FOREIGN KEY (id_profesor) REFERENCES PROFESOR(id_profesor)
);

-- TABLA INTERMEDIA: EVENTO <-> ESTUDIANTE
CREATE TABLE EVENTO_ESTUDIANTE (
    id_evento           NUMBER,
    numrun_estudiante   NUMBER,
    PRIMARY KEY (id_evento, numrun_estudiante),
    FOREIGN KEY (id_evento) REFERENCES EVENTO(id_evento),
    FOREIGN KEY (numrun_estudiante) REFERENCES ESTUDIANTE(numrun)
);

-- SECUENCIA PARA IDs DE EVENTOS
CREATE SEQUENCE SEQ_EVENTO START WITH 1 INCREMENT BY 1;
-- SECUENCIAS PARA IDs AUTO-INCREMENTALES
CREATE SEQUENCE SEQ_PROFESOR START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TRACK START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PROYECTO START WITH 101 INCREMENT BY 1;