SET SERVEROUTPUT ON;

DECLARE
    -- Cursor PrinciPal Para recorrer los TRACKS.
    CURSOR C_TRACKS IS
        SELECT ID_TRACK, NOMBRE FROM TRACK;

    -- Cursor anidado Para los PROYECTOS de un TRACK.
    CURSOR C_PROYECTOS(P_ID_TRACK NUMBER) IS
        SELECT ID_PROYECTO, NOMBRE FROM PROYECTO WHERE ID_TRACK = P_ID_TRACK;

    -- Cursor anidado Para el ESTUDIANTE de un PROYECTO.
    CURSOR C_ESTUDIANTE(P_ID_PROYECTO NUMBER) IS
        SELECT PNOMBRE, PAPELLIDO FROM ESTUDIANTE WHERE ID_PROYECTO = P_ID_PROYECTO;

BEGIN
    -- Recorre cada TRACK.
    FOR R_TRACK IN C_TRACKS LOOP
        DBMS_OUTPUT.PUT_LINE('');
        DBMS_OUTPUT.PUT_LINE('--- TRACK: ' || R_TRACK.NOMBRE || ' ---');

        -- Recorre cada PROYECTO dentro del TRACK.
        FOR R_PROYECTO IN C_PROYECTOS(R_TRACK.ID_TRACK) LOOP
            DBMS_OUTPUT.PUT_LINE('  > Proyecto: ' ||R_PROYECTO.NOMBRE);

            -- Busca el ESTUDIANTE asignado al PROYECTO.
            FOR R_ESTUDIANTE IN C_ESTUDIANTE(R_PROYECTO.ID_PROYECTO) LOOP
                DBMS_OUTPUT.PUT_LINE('    - Estudiante: ' || R_ESTUDIANTE.PNOMBRE || ' ' || R_ESTUDIANTE.PAPELLIDO);
            END LOOP;
        END LOOP;
    END LOOP;
END;
/